name: Dev

on:
  push:
    branches: [feature/**]

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: dev
    permissions:
      contents: read
      id-token: write
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create .env
        run: |
          echo "NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}" >> .env
          echo "NEXT_PUBLIC_BACKEND_ENDPOINT=${{ secrets.NEXT_PUBLIC_BACKEND_ENDPOINT }}" >> .env
          echo "NEXT_PUBLIC_AUTH0_DOMAIN=${{ secrets.NEXT_PUBLIC_AUTH0_DOMAIN }}" >> .env
          echo "NEXT_PUBLIC_AUTH0_CLIENT_ID=${{ secrets.NEXT_PUBLIC_AUTH0_CLIENT_ID }}" >> .env
      - name: Install Dependencies
        run: npm ci
      - name: Build App
        run: npm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
