name: UI Test

on:
  push:
    paths:
      - src/**

jobs:
  install:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - name: Cache node_modules
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci
  unit-test:
    needs: install
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - name: Restore node_modules
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Run Unit Tests
        run: npm test
